### ISSUE TITLE
Phone Number Or Id Can't Send Messages

### ISSUE THREAD

**Issue by simplyfaster** [sajuthankappan/whatsapp-cloud-api-rs#3]
Hi @sajuthankappan 
I've try to fill phone_number_id, but it show log

Error: UnexpectedError("{\"error\":{\"message\":\"Unsupported post request. Object with ID 'XXXXX' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https:\\/\\/developers.facebook.com\\/docs\\/graph-api\",\"type\":\"GraphMethodException\",\"code\":100,\"error_subcode\":33,\"fbtrace_id\":\"AXfu0NKfYelIG2VlOmIfK3C\"}}")

what correct number or id in it?

**Comment by sajuthankappan** [comment]
@simplyfaster - I think you have given an invalid/incorrect phone_number_id. Please note, it is not the phone number.
You can get the phone number id from the facebook developer app dashboard. 
Have you given the right phone number id?

**Comment by sajuthankappan** [comment]
Also, please check if you are able to send messages using curl or postman. If it works in curl/postman, it will likely work in the code also. If it works in curl/postman, but not through the code, please reply..
