### ISSUE TITLE
Does this project bing maintain? 

### ISSUE THREAD

**Issue by barel-mishal** [sajuthankappan/whatsapp-cloud-api-rs#4]

**Comment by sajuthankappan** [comment]
Short answer is "Yes" :)

Long answer.. 
Saying this, I havn't got time to upgrade to FB API v18 yet.  (It is still using v15).
If this is what you are looking for? Please let me know. I can make this upgrade really quick (unless there are some surprises).

If anything else, please feel free to create an issue / add you comment here..

**Comment by sajuthankappan** [comment]
Upgraded FB API version to v17 a little while back.  HTH, if you are looking for that.
